name: ToolsWithJerry
version: ${version}
authors:
  - T4ron_
  - GameWithJerry
main: de.gamewithjerry.toolswithjerry.Main
api-version: 1.16
commands:
  spawn:
    description: Gehe zu deinem Bett oder zum Hauptspawn, wenn du kein Bett hast.
